<?php
/**
 * Created by PhpStorm.
 * User: Etudiant
 * Date: 07/01/2019
 * Time: 14:44
 */

namespace App\Form;


use App\Entity\Unavailability;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;

class UnavailabilityAdminType extends UnavailabilityType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub

        $builder
            ->add('type', ChoiceType::class, [
                'label' => 'Type de réservation',
                'choices' => [
                    'réunion' => Unavailability::REUNION,
                    'autre' => Unavailability::AUTRE
                ],
                'expanded' => false,
                'multiple' => false
            ])
            ->add('organiser', EntityType::class, [
                'label' => 'Organisateur',
                'class' => User::class,
                'choice_label' => 'email',
                'expanded' => false,
                'multiple' => false,
            ]);

    }

}